apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: nyc-r3s1
  annotations:
    iam.gke.io/gcp-service-account: nycr3s1-backend-runtime@nychacksishv-core-20260808.iam.gserviceaccount.com
